name: Audit

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
      - develop
      - v2.0-dev
  pull_request:
    branches:
      - master
      - develop
      - v2.0-dev

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
