name: Format

on:
  push:
    branches:
      - master
      - develop
      - v2.0-dev
  pull_request:
    branches:
      - master
      - develop
      - v2.0-dev
    paths-ignore:
      - "docs/**"
      - "specification/**"

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install rustfmt with nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
